const ROLES = {
  HEAD: "HEAD",
  ADMIN: "ADMIN",
  USER: "USER"
};

const TASK_STATUS = {
  PENDING: "Pending",
  IN_PROGRESS: "In Progress",
  COMPLETED: "Completed",
  OVERDUE: "Overdue",
  CANCELLED: "Cancelled"
};

const MESSAGE_TYPES = {
  TEXT: "TEXT",
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_COMPLETED: "TASK_COMPLETED",
  REPORT_CREATED: "REPORT_CREATED",
  SYSTEM: "SYSTEM"
};

const REFERENCE_TYPES = {
  MESSAGE: "MESSAGE",
  TASK: "TASK",
  REPORT: "REPORT",
  TASK_UPDATE: "TASK_UPDATE",
  SYSTEM: "SYSTEM"
};

module.exports = {
  ROLES,
  TASK_STATUS,
  MESSAGE_TYPES,
  REFERENCE_TYPES
};
